# Generated by Django 4.2.5 on 2023-09-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
