# Generated by Django 4.2.5 on 2023-10-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='calificacion_promedio',
        ),
    ]
