# Generated by Django 4.2.5 on 2023-11-03 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acceso', '0015_alter_tipousuario_usuario'),
        ('redsocial', '0003_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.mascota'),
        ),
        migrations.DeleteModel(
            name='SolicitudAmistad',
        ),
    ]
