# Generated by Django 4.2.5 on 2023-09-26 22:49

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuenoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='duenos_mascotas_custom', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='duenos_mascotas_custom', to='auth.permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento_mascota', models.DateField(blank=True, null=True)),
                ('genero_mascota', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('historial_medico', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='mascotas/')),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('vacunacion', models.TextField(blank=True)),
                ('comportamiento', models.TextField(blank=True)),
                ('alimentacion', models.TextField(blank=True)),
                ('entrenamiento', models.TextField(blank=True)),
                ('otros_cuidados', models.TextField(blank=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.duenomascota')),
            ],
        ),
    ]
