# Generated by Django 4.2.5 on 2023-09-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_alter_duenomascota_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenomascota',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='duenomascota',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='duenomascota',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
