# Generated by Django 4.2.5 on 2023-09-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_alter_duenomascota_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenomascota',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
