# Generated by Django 4.2.5 on 2023-10-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0005_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenomascota',
            name='tiene_mascota',
            field=models.BooleanField(default=False),
        ),
    ]
