# Generated by Django 4.2.5 on 2023-10-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0008_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
