# Generated by Django 4.2.5 on 2023-10-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0009_alter_tipousuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenomascota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
