# Generated by Django 4.2.5 on 2023-10-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0010_alter_duenomascota_id_alter_mascota_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenomascota',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
