# Generated by Django 4.2.5 on 2023-10-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0011_alter_duenomascota_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenomascota',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
