# Generated by Django 4.2.5 on 2023-11-02 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0013_alter_tipousuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
