# Generated by Django 4.2.5 on 2023-11-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0016_especie_raza_alter_mascota_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenomascota',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Prefiero no decirlo', 'Prefiero no decirlo'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
